### ISSUE TITLE
AppImage not available on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [VirtualPhotonics/MieSimulatorGUI#1]
> Click on “release” to get latest releases. Users can download Windows Installer or Linux appImage.

Unfortunately the AppImage is not available for download there.

**Comment by janakarana** [comment]
We found some issues with the AppImage. It will be uploaded soon.

**Comment by janakarana** [comment]
Thanks for waiting. AppImage is available for download now.

**Comment by janakarana** [comment]
The issue was resolved

**Comment by ivan-hc** [comment]
hi @janakarana in api.github.com exists a first reference to https://github.com/VirtualPhotonics/MieSimulatorGUI/releases/download/Version_2.0/MieSimulatorGUI_v2_0-x86_64.AppImage
```
curl -Ls https://api.github.com/repos/VirtualPhotonics/MieSimulatorGUI/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*mage$" | head -1
```
...but no real AppImage is available (see https://github.com/ivan-hc/amcheck/actions/runs/17186288400/job/48755778920)

**Comment by janakarana** [comment]
The link was a comment and has been removed. The link will be added once the Appimage is uploaded.
