### ISSUE TITLE
scattering and reduced scattering changes by factor of 2 over V1.05 

### ISSUE THREAD

**Issue by gtkenned** [VirtualPhotonics/MieSimulatorGUI#2]
mu and musp parameters calculated using version 1.07 are a factor of 2 higher than in 1.05.
I have run the same numbers through Scott Prahl's calculator and the output agree with V1.05
g is the same in all versions

**Comment by janakarana** [comment]
After releasing v1.0.5, we made major changes to the code to handle spheres with complex refractive index. To maintain faster simulations for real computations, we introduced two functions; one function to handle "real" refractive index inputs and another function to handle "complex" refractive index inputs. Unfortunately, a bug has been created during the process. In v1.0.6 and v1.0.7, the simulated scattering cross section, scattering coefficient (mus), reduced scattering coefficient (musp) and phase function values are off by a factor of 2 for "real" refractive index inputs. We fix that bug and release a new version (v1.0.8). All v1.0.6 and v1.0.7 users are advised to download the new version (v1.0.8). The version 1.0.5 provides correct results.
