### ISSUE TITLE
Technical question

### ISSUE THREAD

**Issue by swawa** [VirtualPhotonics/MieSimulatorGUI#8]
Thanks for first to help visualize and develop a better understanding of the correlation of particle size and mie scattering. 
In the anisotropy panel as well as in the display data window a percentage of forward and backward scattering fractions are given.
How exactly are the terms "forward" and "backward" to be understood in this context? Does it mean angles of exactly 0 and 180 degree or does it include an angular range in the forward and backward direction?

Thanks for helping understandig.
Swawa

**Comment by Spurs15437** [comment]
I think that the Forward means 0-90, and backward means 90-180.

**Comment by swawa** [comment]
Ok. Thanks a lot
